hello/urls.py
from . import views
from django.urls import path
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greet, name="greet")
]

newyear/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("", views.index, name="index")
]

rev1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
]

tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

hello/models.py
from django.db import models

# Create your models here.

newyear/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")
def  greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

newyear/views.py
import datetime
from django.shortcuts import render

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

tasks/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

# Create your views here.


class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")

def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })
def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
        "form": form
    })

    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang=""en>
    <head>
        <title>hello</title>
    </head>
    <body>
        <h1>Hello, {{ name }}</h1>
    </body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>hello</title>
    </head>
    <body>
        <h1>Hello world</h1>
    </body>
</html>

newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Is it new year</title>
        <link href ="{% static 'newyear/styles.CSS' %}" rel="stylesheet">
    </head>
    <body>
        {% if newyear %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}
    </body>
</html>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
        <h1>Add Tasks</h1>
        <form action="{% url 'tasks:add' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit">
        </form>
        <a href="{% url 'tasks:index' %}">view task</a>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
        <h1>Tasks</h1>
        <ul>
            {% for task in tasks %}
                <li>{{ task }}</li>
                {% empty %}
                    <li>No tasks</li>
            {% endfor %}
        </ul>
        <a href="{% url 'tasks:add' %}">Add a new task</a>
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>tasks</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>